#GET http://localhost:8080/api/ljubimci/ljubimciIVlasnici

#GET http://localhost:8080/api/ljubimci/ljubimciIVlasnici?searchText=za&attribute=adresa

#GET http://localhost:8080/api/ljubimci/ljubimciIVlasniciJSON

#GET http://localhost:8080/api/ljubimci/id/2

#GET http://localhost:8080/api/ljubimci/adresa/Zagreb

#GET http://localhost:8080/api/ljubimci/ime/Lolipop

#GET http://localhost:8080/api/ljubimci/vrsta/pas



#POST http://localhost:8080/api/ljubimci
#Content-Type: application/json
#
#{
#    "imeLjubimac": "Zara",
#    "vrsta": "orao",
#    "spol": "muški",
#    "dob": 2,
#    "boja": "smeđa",
#    "prehrana": "mesožder",
#    "adresa": "Sumag",
#    "veterinar": "Dr. Janko Jelačić",
#    "imeVlasnika": "Marko",
#    "prezimeVlasnika": "Markičević"
#}

#PUT http://localhost:8080/api/ljubimci/1
#Content-Type: application/json
#
#{
#    "imeLjubimac": "Lasdf",
#    "vrsta": "pas",
#    "spol": "muški",
#    "dob": 14,
#    "boja": "smeđa",
#    "prehrana": "mesožder",
#    "adresa": "Zagreb",
#    "veterinar": "Dr. Ana Kovač",
#    "imeVlasnika": "Marko",
#    "prezimeVlasnika": "Sanader"
#}

#DELETE http://localhost:8080/api/ljubimci/10

#GET http://localhost:8080/api/vlasnici

#PATCH http://localhost:8080/api/ljubimci/ljubimciIVlasniciJSON
